/*
 * This file is generated by jOOQ.
 */
package io.github.sd3v.mflashcardsbe.jooq.tables;


import io.github.sd3v.mflashcardsbe.jooq.Keys;
import io.github.sd3v.mflashcardsbe.jooq.Public;
import io.github.sd3v.mflashcardsbe.jooq.tables.records.DeckRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Deck extends TableImpl<DeckRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.deck</code>
     */
    public static final Deck DECK = new Deck();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeckRecord> getRecordType() {
        return DeckRecord.class;
    }

    /**
     * The column <code>public.deck.id</code>.
     */
    public final TableField<DeckRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.deck.name</code>.
     */
    public final TableField<DeckRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.deck.slug</code>.
     */
    public final TableField<DeckRecord, String> SLUG = createField(DSL.name("slug"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.deck.type</code>.
     */
    public final TableField<DeckRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.deck.language</code>.
     */
    public final TableField<DeckRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.deck.tags</code>.
     */
    public final TableField<DeckRecord, String> TAGS = createField(DSL.name("tags"), SQLDataType.VARCHAR, this, "");

    private Deck(Name alias, Table<DeckRecord> aliased) {
        this(alias, aliased, null);
    }

    private Deck(Name alias, Table<DeckRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.deck</code> table reference
     */
    public Deck(String alias) {
        this(DSL.name(alias), DECK);
    }

    /**
     * Create an aliased <code>public.deck</code> table reference
     */
    public Deck(Name alias) {
        this(alias, DECK);
    }

    /**
     * Create a <code>public.deck</code> table reference
     */
    public Deck() {
        this(DSL.name("deck"), null);
    }

    public <O extends Record> Deck(Table<O> child, ForeignKey<O, DeckRecord> key) {
        super(child, key, DECK);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DeckRecord, Long> getIdentity() {
        return (Identity<DeckRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DeckRecord> getPrimaryKey() {
        return Keys.DECK_PKEY;
    }

    @Override
    public Deck as(String alias) {
        return new Deck(DSL.name(alias), this);
    }

    @Override
    public Deck as(Name alias) {
        return new Deck(alias, this);
    }

    @Override
    public Deck as(Table<?> alias) {
        return new Deck(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Deck rename(String name) {
        return new Deck(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Deck rename(Name name) {
        return new Deck(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Deck rename(Table<?> name) {
        return new Deck(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
