/*
 * This file is generated by jOOQ.
 */
package io.github.sd3v.mflashcardsbe.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Deck implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String name;
    private final String slug;
    private final String type;
    private final String description;
    private final String language;
    private final String tags;

    public Deck(Deck value) {
        this.id = value.id;
        this.name = value.name;
        this.slug = value.slug;
        this.type = value.type;
        this.description = value.description;
        this.language = value.language;
        this.tags = value.tags;
    }

    public Deck(
        Long id,
        String name,
        String slug,
        String type,
        String description,
        String language,
        String tags
    ) {
        this.id = id;
        this.name = name;
        this.slug = slug;
        this.type = type;
        this.description = description;
        this.language = language;
        this.tags = tags;
    }

    /**
     * Getter for <code>public.deck.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.deck.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.deck.slug</code>.
     */
    public String getSlug() {
        return this.slug;
    }

    /**
     * Getter for <code>public.deck.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Getter for <code>public.deck.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>public.deck.language</code>.
     */
    public String getLanguage() {
        return this.language;
    }

    /**
     * Getter for <code>public.deck.tags</code>.
     */
    public String getTags() {
        return this.tags;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Deck (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(slug);
        sb.append(", ").append(type);
        sb.append(", ").append(description);
        sb.append(", ").append(language);
        sb.append(", ").append(tags);

        sb.append(")");
        return sb.toString();
    }
}
