/*
 * This file is generated by jOOQ.
 */
package io.github.sd3v.mflashcardsbe.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Flashcard implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String front;
    private final String back;
    private final String example;
    private final Long deckId;

    public Flashcard(Flashcard value) {
        this.id = value.id;
        this.front = value.front;
        this.back = value.back;
        this.example = value.example;
        this.deckId = value.deckId;
    }

    public Flashcard(
        Long id,
        String front,
        String back,
        String example,
        Long deckId
    ) {
        this.id = id;
        this.front = front;
        this.back = back;
        this.example = example;
        this.deckId = deckId;
    }

    /**
     * Getter for <code>public.flashcard.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.flashcard.front</code>.
     */
    public String getFront() {
        return this.front;
    }

    /**
     * Getter for <code>public.flashcard.back</code>.
     */
    public String getBack() {
        return this.back;
    }

    /**
     * Getter for <code>public.flashcard.example</code>.
     */
    public String getExample() {
        return this.example;
    }

    /**
     * Getter for <code>public.flashcard.deck_id</code>.
     */
    public Long getDeckId() {
        return this.deckId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Flashcard (");

        sb.append(id);
        sb.append(", ").append(front);
        sb.append(", ").append(back);
        sb.append(", ").append(example);
        sb.append(", ").append(deckId);

        sb.append(")");
        return sb.toString();
    }
}
