/*
 * This file is generated by jOOQ.
 */
package io.github.sd3v.mflashcardsbe.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Noun implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String name;
    private final String description;
    private final String article;
    private final String fullname;
    private final String tags;

    public Noun(Noun value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.article = value.article;
        this.fullname = value.fullname;
        this.tags = value.tags;
    }

    public Noun(
        Long id,
        String name,
        String description,
        String article,
        String fullname,
        String tags
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.article = article;
        this.fullname = fullname;
        this.tags = tags;
    }

    /**
     * Getter for <code>public.noun.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.noun.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.noun.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>public.noun.article</code>.
     */
    public String getArticle() {
        return this.article;
    }

    /**
     * Getter for <code>public.noun.fullname</code>.
     */
    public String getFullname() {
        return this.fullname;
    }

    /**
     * Getter for <code>public.noun.tags</code>.
     */
    public String getTags() {
        return this.tags;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Noun (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(article);
        sb.append(", ").append(fullname);
        sb.append(", ").append(tags);

        sb.append(")");
        return sb.toString();
    }
}
