/*
 * This file is generated by jOOQ.
 */
package io.github.sd3v.mflashcardsbe.jooq.tables.records;


import io.github.sd3v.mflashcardsbe.jooq.tables.Deck;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeckRecord extends UpdatableRecordImpl<DeckRecord> implements Record7<Long, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.deck.id</code>.
     */
    public DeckRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.deck.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.deck.name</code>.
     */
    public DeckRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.deck.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.deck.slug</code>.
     */
    public DeckRecord setSlug(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.deck.slug</code>.
     */
    public String getSlug() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.deck.type</code>.
     */
    public DeckRecord setType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.deck.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.deck.description</code>.
     */
    public DeckRecord setDescription(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.deck.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.deck.language</code>.
     */
    public DeckRecord setLanguage(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.deck.language</code>.
     */
    public String getLanguage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.deck.tags</code>.
     */
    public DeckRecord setTags(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.deck.tags</code>.
     */
    public String getTags() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Deck.DECK.ID;
    }

    @Override
    public Field<String> field2() {
        return Deck.DECK.NAME;
    }

    @Override
    public Field<String> field3() {
        return Deck.DECK.SLUG;
    }

    @Override
    public Field<String> field4() {
        return Deck.DECK.TYPE;
    }

    @Override
    public Field<String> field5() {
        return Deck.DECK.DESCRIPTION;
    }

    @Override
    public Field<String> field6() {
        return Deck.DECK.LANGUAGE;
    }

    @Override
    public Field<String> field7() {
        return Deck.DECK.TAGS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSlug();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public String component6() {
        return getLanguage();
    }

    @Override
    public String component7() {
        return getTags();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSlug();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public String value6() {
        return getLanguage();
    }

    @Override
    public String value7() {
        return getTags();
    }

    @Override
    public DeckRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DeckRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DeckRecord value3(String value) {
        setSlug(value);
        return this;
    }

    @Override
    public DeckRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public DeckRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public DeckRecord value6(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public DeckRecord value7(String value) {
        setTags(value);
        return this;
    }

    @Override
    public DeckRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeckRecord
     */
    public DeckRecord() {
        super(Deck.DECK);
    }

    /**
     * Create a detached, initialised DeckRecord
     */
    public DeckRecord(Long id, String name, String slug, String type, String description, String language, String tags) {
        super(Deck.DECK);

        setId(id);
        setName(name);
        setSlug(slug);
        setType(type);
        setDescription(description);
        setLanguage(language);
        setTags(tags);
    }

    /**
     * Create a detached, initialised DeckRecord
     */
    public DeckRecord(io.github.sd3v.mflashcardsbe.jooq.tables.pojos.Deck value) {
        super(Deck.DECK);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setSlug(value.getSlug());
            setType(value.getType());
            setDescription(value.getDescription());
            setLanguage(value.getLanguage());
            setTags(value.getTags());
        }
    }
}
