/*
 * This file is generated by jOOQ.
 */
package io.github.sd3v.mflashcardsbe.jooq;


import io.github.sd3v.mflashcardsbe.jooq.tables.Deck;
import io.github.sd3v.mflashcardsbe.jooq.tables.Flashcard;
import io.github.sd3v.mflashcardsbe.jooq.tables.FlywaySchemaHistory;
import io.github.sd3v.mflashcardsbe.jooq.tables.Noun;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.deck</code>.
     */
    public static final Deck DECK = Deck.DECK;

    /**
     * The table <code>public.flashcard</code>.
     */
    public static final Flashcard FLASHCARD = Flashcard.FLASHCARD;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.noun</code>.
     */
    public static final Noun NOUN = Noun.NOUN;
}
